### ISSUE TITLE
Remove the spaces?

### ISSUE THREAD

**Issue by elliot-zzh** [tats-u/prettier-plugin-md-nocjsp#1]
Well it seems like this plugin only ignore the default behavior in Prettier v2.X, but it won't remove those existing spaces. Is it possible to provide a way to remove those spaces while formatting? I know sometimes the existing spaces should be preserved for specific need, so I would just like to have an optional feature, deleting those old spaces which is simply caused by Prettier.

**Comment by tats-u** [comment]
Have you tried the `quickFix` option written in the README? It should work for your case.

**Comment by elliot-zzh** [comment]
Yes that does work. Sorry that I didn't read the README carefully, and thanks for your extremely quick help!
