### ISSUE TITLE
あなたの名前を Prettier v3 のリリースブログに掲載してもよいですか？

### ISSUE THREAD

**Issue by sosukesuzuki** [tats-u/prettier-plugin-md-nocjsp#2]
こんにちは、Prettier のメンテナーの鈴木です。

https://github.com/prettier/prettier/pull/13436#discussion_r1172231957 でも言及させていただいたのですが、反応がなく、メールアドレスなどの連絡先もわからなかったので、やや不適切だとは理解しつつ、このリポジトリの issue という場を借りています。

issue のタイトルの通り、Tatsunori Uchino さんの名前を Prettier v3 のリリースブログに掲載してもよろしいでしょうか？

Prettier チームとして、v3 における Uchino さんの大きな貢献に感謝しています。

特に私はメンテナーであると同時に、日常的に日本語を使う当事者でもあるため、この問題に強い関心があり、実装を試みたこともありました。しかし、想像していたよりも考慮すべき事項が多く、私は諦めてしまいました。Uchino さんが長い間この問題のために時間を使い、解決してくれたことに本当に感謝しています。

具体的には https://github.com/prettier/prettier/pull/13436#discussion_r1172231957 のように記載させていただければと思います。もし、名前をこのような目立つ場所に記載されるのが嫌だという場合は遠慮なく言ってください。当然ですが、その場合でも我々から Uchino さんへの感謝は変わりません。

**Comment by tats-u** [comment]
@sosukesuzuki なぜか届いていませんでした。OKです。多分ないと思いますが万が一漢字表記が必要な際にはお申し付けください。

**Comment by sosukesuzuki** [comment]
ありがとうございます。
